console.log('main.js is connected!');

// maybe you want to use `fetch` to make your call....
// maybe you will want to hook `fetch` up to your search form's submission....
// maybe we did that in a lab the other day...... 
// HMM! no more hints! just do it!!!
